---
abstract: 'Pluggable (lite) authentication and authorization server.'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PlugAuth-Lite
recommends:
  EV: 0
requires:
  Mojolicious: 3.86
  autodie: 0
  perl: 5.010
resources:
  bugtracker: https://github.com/plicease/plugauth-lite/issues
  homepage: http://perl.wdlabs.com/PlugAuth-Lite/
  repository: git://github.com/plicease/plugauth-lite.git
version: 0.07
