---
abstract: 'Pluggable (lite) authentication and authorization server.'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PlugAuth-Lite
requires:
  Mojolicious: 3.86
  perl: 5.010001
resources:
  bugtracker: https://github.com/plicease/plugauth-lite/issues
  homepage: http://perl.wdlabs.com/PlugAuth-Lite/
  repository: git://github.com/plicease/plugauth-lite.git
version: 0.01
